apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:0.54.0
        ports:
        - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            value: mongouser
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            value: mongopwd
          - name: ME_CONFIG_MONGODB_PORT
            value: "27017"
          - name: ME_CONFIG_MONGODB_SERVER
            value: mongodb
          